In [ ]:
import numpy as np

In [ ]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [ ]:
a= np.array(arr)
print(type(a)) 
print(a.shape) 
print(a.dtype) 

<class 'numpy.ndarray'>
(4,)
int64


In [ ]:
print(a.ndim)

1


In [ ]:
b = np.array([[1,2,3], [4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)

2


In [ ]:
b.shape

(2, 3)

In [ ]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(4,)
int64


In [ ]:
print(a.ndim)

1


In [ ]:
np.random.random((2,3))


array([[0.46919652, 0.48965533, 0.33893209],
       [0.11387783, 0.93065539, 0.07373259]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0,5.0,6.0], [9.0,8.0,7.0]])
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [ ]:
c * d 

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [ ]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [ ]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [ ]:
a[0]
a[3]
b[0,0]
b[1,2]
c[0, 1]

8.0

In [ ]:
a[0]

6

In [ ]:
a[3]

9

In [ ]:
b[0,0]

1

In [ ]:
b[1,2]

6

In [ ]:
c[0,1]

8.0

In [ ]:
d[1, 0:2]

array([9., 8.])

In [ ]:
e = np.array([[10,11,12], [13,14,15], [16,17,18],[19,20,21]])

In [ ]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [ ]:
e[[2,0,3,1], [2,1,0,2]]

array([18, 11, 19, 15])

In [ ]:
e[e>15]

array([16, 17, 18, 19, 20, 21])